const express = require('express');
const { default: makeWASocket, useMultiFileAuthState, DisconnectReason } = require('@whiskeysockets/baileys');
const pino = require('pino');
const QRCode = require('qrcode');
let AgenticOrg;
try {
    AgenticOrg = require('agenticorg-sdk').AgenticOrg;
} catch (e) {
    AgenticOrg = null;
}

const app = express();
app.use(express.json());

let currentQR = null;
let clientStatus = 'STARTING';
let sock = null;

// ==================================================================
// 🔑 AgenticOrg Configuration
// ==================================================================
const AGENTICORG_API_KEY = process.env.AGENTICORG_API_KEY || '';
// The agent type or workflow you created in the platform (e.g., 'chat_agent', 'support_triage', 'ap_processor')
const AGENT_TYPE = process.env.AGENT_TYPE || 'chat_agent';

let aiClient = null;
if (AgenticOrg && AGENTICORG_API_KEY) {
    aiClient = new AgenticOrg({ apiKey: AGENTICORG_API_KEY });
    console.log(`🤖 AgenticOrg client initialized for agent: ${AGENT_TYPE}`);
} else {
    console.log('⚠️ AgenticOrg API Key not set. Running in echo/ping mode.');
}

// Helper function for IST Date
function getISTDate() {
    return new Date();
}

// ==================================================================
// 📱 WhatsApp Engine (Baileys)
// ==================================================================
async function startWhatsApp() {
    const { state, saveCreds } = await useMultiFileAuthState('./baileys_auth');

    sock = makeWASocket({
        auth: state,
        logger: pino({ level: 'silent' }),
        printQRInTerminal: false
    });

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect, qr } = update;

        if (qr) {
            clientStatus = 'AWAITING_SCAN';
            QRCode.toDataURL(qr, (err, url) => {
                if (!err) currentQR = url;
            });
            console.log('📱 New QR code generated. Scan via web page.');
        }

        if (connection === 'open') {
            clientStatus = 'READY';
            currentQR = null;
            console.log('✅ WhatsApp Agent is ONLINE and READY!');
        }

        if (connection === 'close') {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            clientStatus = 'DISCONNECTED';
            console.log(`⚠️ Connection closed. Reconnecting: ${shouldReconnect}`);
            if (shouldReconnect) {
                startWhatsApp();
            }
        }
    });

    // Handle Incoming WhatsApp Messages
    sock.ev.on('messages.upsert', async ({ messages, type }) => {
        if (type !== 'notify') return;

        for (const msg of messages) {
            if (!msg.message) continue;

            const senderJid = msg.key.remoteJid;
            if (senderJid === 'status@broadcast') continue;

            // Extract message body
            const text = msg.message.conversation || msg.message.extendedTextMessage?.text || '';
            const isFromMe = msg.key.fromMe;
            const senderName = msg.pushName || 'User';

            // Ignore empty messages or our own messages (unless testing with !ping)
            if (!text) continue;
            if (isFromMe && text.toLowerCase() !== '!ping') continue;

            console.log(`[Message from ${senderName} (${senderJid})]: ${text}`);

            // 1. Quick test command !ping
            if (text.toLowerCase() === '!ping') {
                await sock.sendMessage(senderJid, { text: 'pong! 🏓 AgenticOrg WhatsApp bridge is active.' });
                continue;
            }

            // 2. Process with AgenticOrg Virtual Employee / Workflow
            if (aiClient) {
                try {
                    console.log(`🤖 Forwarding message to AgenticOrg Agent [${AGENT_TYPE}]...`);

                    // Run the agent. This automatically saves the execution, memory, and outputs into your platform!
                    const runResult = await aiClient.agents.run(AGENT_TYPE, {
                        inputs: {
                            sender_id: senderJid,
                            sender_name: senderName,
                            message: text,
                            timestamp: msg.messageTimestamp ? String(msg.messageTimestamp) : String(Date.now())
                        }
                    });

                    console.log('AgenticOrg output:', runResult);

                    // Extract the reply generated by the agent
                    const agentReply = runResult.output?.reply || runResult.output?.response || runResult.output || runResult.response;

                    if (agentReply) {
                        const replyString = typeof agentReply === 'object' ? JSON.stringify(agentReply, null, 2) : String(agentReply);
                        await sock.sendMessage(senderJid, { text: replyString });
                    }
                } catch (err) {
                    console.error('❌ Error executing AgenticOrg Agent:', err.message || err);
                    await sock.sendMessage(senderJid, { text: 'Sorry, I encountered an issue processing your request.' });
                }
            } else {
                console.log('ℹ️ AgenticOrg API Key not configured in environment variables.');
            }
        }
    });
}

startWhatsApp();

// ==================================================================
// 🩺 Health Check & Ping (Keeps Render Service Awake)
// ==================================================================
app.get('/health', (req, res) => {
    res.json({
        status: 'ok',
        whatsappStatus: clientStatus,
        agenticOrgConfigured: Boolean(aiClient),
        timeIST: getISTDate().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
    });
});

app.get('/ping', (req, res) => res.status(200).send('OK'));

// ==================================================================
// 📱 Web Dashboard (Shows QR & Status)
// ==================================================================
app.get('/', (req, res) => {
    if (clientStatus === 'READY') {
        res.send(`
            <html>
                <body style="font-family: Arial, sans-serif; text-align: center; padding-top: 50px;">
                    <h2 style="color: #25D366;">✅ WhatsApp Agent is Online & Connected!</h2>
                    <p>Connected to AgenticOrg Agent: <strong>${AGENT_TYPE}</strong></p>
                    <p>Status: <strong>${clientStatus}</strong></p>
                    <p>Send a message on WhatsApp to interact with your Virtual Employee.</p>
                </body>
            </html>
        `);
    } else if (currentQR) {
        res.send(`
            <html>
                <body style="font-family: Arial, sans-serif; text-align: center; padding-top: 50px;">
                    <h2>📱 Scan this QR Code with WhatsApp</h2>
                    <img src="${currentQR}" width="280" style="border: 1px solid #ccc; padding: 10px; border-radius: 8px;" />
                    <p>Status: <strong>${clientStatus}</strong></p>
                    <script>setTimeout(() => location.reload(), 15000);</script>
                </body>
            </html>
        `);
    } else {
        res.send(`
            <html>
                <body style="font-family: Arial, sans-serif; text-align: center; padding-top: 50px;">
                    <h2>⏳ WhatsApp Status: ${clientStatus}</h2>
                    <script>setTimeout(() => location.reload(), 3000);</script>
                </body>
            </html>
        `);
    }
});

// ==================================================================
// 🚀 Outbound API: Trigger WhatsApp messages from your platform
// ==================================================================
app.post('/api/send-message', async (req, res) => {
    const { to, message } = req.body;
    if (!to || !message) {
        return res.status(400).json({ error: 'Missing "to" or "message"' });
    }
    if (!sock || clientStatus !== 'READY') {
        return res.status(503).json({ error: 'WhatsApp client is not ready' });
    }

    try {
        const jid = to.includes('@s.whatsapp.net') ? to : `${to.replace(/[^0-9]/g, '')}@s.whatsapp.net`;
        await sock.sendMessage(jid, { text: message });
        res.json({ success: true, message: 'Message sent successfully' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ==================================================================
// 🚀 SERVER START
// ==================================================================
const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
    console.log('🚀 Server started...');
    console.log(`✅ Server running on port ${PORT}`);
});
